### ISSUE TITLE
bin/mysql_dump_stats errors on tables without any indexes

### ISSUE THREAD

**Issue by gabetax** [burrito-brothers/shiba#19]
We have a handful of tables that don't have any indexes. Some use the [`BLACKHOLE` storage engine](https://dev.mysql.com/doc/refman/8.0/en/blackhole-storage-engine.html). Another had its indexes removed in preparation for dropping it. Regardless, we get the following stack dump due to the disparity of `SHOW TABLES` and `information_schema.statistics`

```
$ bin/mysql_dump_stats ...
Traceback (most recent call last):
	8: from shiba/bin/dump_stats:22:in `<main>'
	7: from shiba/lib/shiba/fuzzer.rb:39:in `fetch_index'
	6: from shiba/lib/shiba/connection/mysql.rb:30:in `each_column_size'
	5: from shiba/lib/shiba/connection/mysql.rb:30:in `each'
	4: from shiba/lib/shiba/connection/mysql.rb:39:in `block in each_column_size'
	3: from shiba/lib/shiba/connection/mysql.rb:39:in `each'
	2: from shiba/lib/shiba/connection/mysql.rb:40:in `block (2 levels) in each_column_size'
	1: from shiba/lib/shiba/fuzzer.rb:40:in `block in fetch_index'
shiba/lib/shiba/index_stats.rb:169:in `set_column_size': couldn't find table: example_table_name (RuntimeError)
```

**Comment by osheroff** [comment]
fixed, won't crash here
