### ISSUE TITLE
bin/mysql_dump_stats errors on large (>1 billion row) tables

### ISSUE THREAD

**Issue by gabetax** [burrito-brothers/shiba#20]
on https://github.com/burrito-brothers/shiba/blob/a433c2d7cc2e9588dbf6e66509e3cdb4bcc5c652/lib/shiba/index_stats.rb#L107-L115

there isn't a final `else` condition. If the table is > 1 billion rows, we crash with:

```
$ bin/mysql_dump_stats ...
Traceback (most recent call last):
	31: from shiba/bin/dump_stats:23:in `<main>'
	30: from shiba/lib/shiba/index_stats.rb:224:in `to_yaml'
	29: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/core_ext.rb:13:in `to_yaml'
	28: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych.rb:441:in `dump'
	27: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:118:in `push'
	26: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:136:in `accept'
	25: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:358:in `visit_Hash'
	24: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:358:in `each'
	23: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:360:in `block in visit_Hash'
	22: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:134:in `accept'
	21: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:518:in `dump_coder'
	20: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:533:in `emit_coder'
	19: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:533:in `each'
	18: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:535:in `block in emit_coder'
	17: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:136:in `accept'
	16: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:358:in `visit_Hash'
	15: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:358:in `each'
	14: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:360:in `block in visit_Hash'
	13: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:134:in `accept'
	12: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:518:in `dump_coder'
	11: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:533:in `emit_coder'
	10: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:533:in `each'
	 9: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:535:in `block in emit_coder'
	 8: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:136:in `accept'
	 7: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:381:in `visit_Array'
	 6: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:389:in `visit_Enumerator'
	 5: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:389:in `each'
	 4: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:389:in `block in visit_Enumerator'
	 3: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:134:in `accept'
	 2: from /opt/rbenv/versions/2.5.3/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:517:in `dump_coder'
	 1: from shiba/lib/shiba/index_stats.rb:120:in `encode_with'
shiba/lib/shiba/index_stats.rb:120:in `>': comparison of Float with nil failed (ArgumentError)
```

**Comment by gabetax** [comment]
Is there any long-term value or cost in a "table ignore list"? flag on mysql_dump_stats? I'm currently maintaining an exclude list inline in `Shiba::Connection::Mysql#tables`

**Comment by osheroff** [comment]
fixed
