### ISSUE TITLE
can't modify frozen NilClass (RuntimeError) for rspec

### ISSUE THREAD

**Issue by dhurba87** [burrito-brothers/shiba#24]
Can someone help?

```
2 problematic queries detected
Report available at /Users/dhurba87/apps/trip101/log/shiba_results/shiba_results-1554780870.html

Finished in 1.86 seconds (files took 11.02 seconds to load)
19 examples, 0 failures
/Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/shiba-0.9.2/lib/shiba/activerecord_integration.rb:90:in `block (2 levels) in when_done': can't modify frozen NilClass (RuntimeError)                                                               
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:287:in `instance_exec'                                                                                                                     
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:287:in `instance_exec_with_rescue'                                                                                                         
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:356:in `run'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `block in run'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `each'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `run'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:485:in `run'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:114:in `block in run_specs'                                                                                                                 
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:54:in `report'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:108:in `run_specs'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:86:in `run'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:24:in `eval'
        from /Users/dhurba87/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by osheroff** [comment]
yup.  the error is a bit odd, looking to see if I can repro this under ruby 2.2.2

**Comment by osheroff** [comment]
i couldn't get anything working under ruby 2.2.2, but maybe just see if https://github.com/burrito-brothers/shiba/pull/25 fixes for ya?

**Comment by dhurba87** [comment]
I tried #25 and there was another issue.
```
/Users/dhurba87/.rvm/gems/ruby-2.2.2/bundler/gems/shiba-0c7525d2c37f/lib/shiba/output.rb:66:in `make_web!': dist/index.html not found. Try running 'rake build_web' (Shiba::Error)
	from /Users/dhurba87/.rvm/gems/ruby-2.2.2/bundler/gems/shiba-0c7525d2c37f/bin/explain:67:in `<main>'

```

**Comment by osheroff** [comment]
ah, yes.  shiba doesn't like being bundled that way (as a git: reference) if that PR fixes the first issue I'll just merge and release.

**Comment by osheroff** [comment]
pushed 0.9.3 with the fixes, try that

**Comment by dhurba87** [comment]
It worked. Thanks.

**Comment by osheroff** [comment]
great!  let us know (here, if you like) how shiba works for you.
