### ISSUE TITLE
Error running on travis

### ISSUE THREAD

**Issue by lloydwatkin** [burrito-brothers/shiba#32]
When running `shiba` on travis I see the following error:

```
1.09s$ bundle exec shiba review --submit
fatal: ambiguous argument 'origin/HEAD...': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
/home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/lib/shiba/review/diff.rb:152:in `paths': Failed to read changes (Shiba::Error)
	from /home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/lib/shiba/review/explain_diff.rb:98:in `changed_files'
	from /home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/lib/shiba/review/explain_diff.rb:53:in `result'
	from /home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/lib/shiba/review/cli.rb:54:in `run'
	from /home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/bin/review:7:in `<main>'
```

I'm running the latest release (0.9.4) and `shiba` is triggered by running the following in my `.travis.yml`:

```yml
after_script:
 - bundle exec shiba review --submit
```

Any idea what could be going wrong?

**Comment by lloydwatkin** [comment]
Dump in verbose mode:

```
Finding default options from CI environment.
diff: 
branch: 
pull_request: false
 origin/HEAD...
fatal: ambiguous argument 'origin/HEAD...': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
/home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/lib/shiba/review/diff.rb:152:in `paths': Failed to read changes (Shiba::Error)
	from /home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/lib/shiba/review/explain_diff.rb:98:in `changed_files'
	from /home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/lib/shiba/review/explain_diff.rb:53:in `result'
	from /home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/lib/shiba/review/cli.rb:54:in `run'
	from /home/travis/build/OLIOEX/api/vendor/bundle/ruby/2.5.0/gems/shiba-0.9.4/bin/review:7:in `<main>'
```

**Comment by lloydwatkin** [comment]
From a pull request review:

```
$ bundle exec shiba review --submit --verbose
Finding default options from CI environment.
diff: 
branch: 32b4b46cadc408d507c1271d3e1b9d9e6269002f
pull_request: 3412
 origin/HEAD...32b4b46cadc408d507c1271d3e1b9d9e6269002f
grep /tmp/shiba/ci.json -e .travis.yml
Updated lines: [[".travis.yml", 20..24]]
No problems found caused by the diff
```

We run CI on every commit that gets pushed up to github, so I'm guessing if the commit isn't linked to a pull request then `shiba` is having issues?
